my:
  config:
    # 0:从酷我api搜索，1:从数据库搜索，尽量小写
    searchFromTrueKuwoApiOrFalseDatabase: 0
    # 酷我api搜索保存到数据库，0:不保存 1:保存
    addApiSearchResultToDatabase: 1

spring:
  datasource:
    username: root
    password: 123456
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8001

mybatis:
  # 注意：对应实体类的路径
  type-aliases-package: com.kuang.pojo
  #指定myBatis的核心配置文件与Mapper映射文件
  mapper-locations: classpath:com/kuang/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true

jasypt:
  encryptor:
    # 指定加密密钥，生产环境请放到启动参数里面
    password: secret
    # 指定解密算法，需要和加密时使用的算法一致
    algorithm: PBEWithMD5AndDES
    # 指定initialization vector类型
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
